# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      # Primary container
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - run:
          name: Display environment information
          command: |
            python --version
            pip -V

      - run:
          name: Install requirements
          command: pip install --user -r requirements.txt
          working_directory: server
         
      - run:
          name: Install boto3
          command: pip install --user boto3
          
      - run:
          name: Install and configure awscli
          command: |
            pip install --user awscli
            export AWS_ACCESS_KEY_ID=Some_Key
            export AWS_SECRET_ACCESS_KEY=Some_Secret_Key
            export AWS_DEFAULT_REGION=ca-central-1
            export AWS_DEFAULT_OUTPUT=json

      - run:
          name: Install DynamoDB Local
          command: |
            mkdir ~/DynamoDBLocal
            cd ~/DynamoDBLocal
            curl -O https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz
            tar -xvzf dynamodb_local_latest.tar.gz
 
      - run:
          name: Start up DynamoDB local
          command: |
            cd ~/DynamoDBLocal/dynamodb_local_latest
            java -Djava.library.pathh=./DynamoDBLocal_lib/ -jar DynamoDBLocal.jar -sharedDb
          background: true

      - run:
          name: Run Test
          command: |
            python api_tests.py
            python db_tests.py
          working_directory: server/chowmein
          
          
