# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    environment:
      - AWS_ACCESS_KEY_ID: "Some_Key"
      - AWS_SECRET_ACCESS_KEY: "Some_Secret_Key"
      - AWS_DEFAULT_REGION: "ca-central-1"
      - AWS_DEFAULT_OUTPUT: "json"

    steps:
      - checkout

      - run:
          name: Install Java
          command: sudo apt-get update && sudo apt-get install default-jdk

      - run:
          name: Display environment information
          command: |
            python --version
            pip -V
            java -version

      - run:
          name: Install requirements
          command: pip install --user -r requirements.txt
          working_directory: server

      - run:
          name: Install boto3
          command: pip install --user boto3

      - run:
          name: Install and configure awscli
          command: pip install --user awscli

      - restore_cache:
          key: v2-dynamodb-cache

      - run:
          name: Install DynamoDB Local
          command: |
            [ -d ~/DynamoDBLocal ] || mkdir ~/DynamoDBLocal && cd ~/DynamoDBLocal 
            [ -d ~/DynamoDBLocal ] || curl -O https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz | tar xz
            [ -d ~/DynamoDBLocal ] || sudo chmod -R ugo+x ~/DynamoDBLocal
      - save_cache:
          key: v2-dynamodb-cache
          paths:
            - ~/DynamoDBLocal
 
      - run:
          name: Start up DynamoDB local
          command: |
            cd ~/DynamoDBLocal && pwd && ls
            java -Djava.library.path=~/DynamoDBLocal/DynamoDBLocal_lib/ -jar ~/DynamoDBLocal/DynamoDBLocal.jar -sharedDb
          background: true

      - run:
          name: Run API Test
          command: python api_tests.py
          working_directory: server/chowmein
          
      - run:
          name: Run DB Test
          command: python db_tests.py
          working_directory: server/chowmein
