# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      # Primary container
      - image: circleci/python:3.6.1
      
      # Service containers
      - image: cnadiminti/dynamodb-local

    steps:
      - checkout

      - run:
          name: Display environment information
          command: |
            python --version
            pip -V
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
          working_directory: server
         
      - run:
          name: Install boto3
          command: pip install boto3
          
      - run:
          name: Install and configure awscli
          command: |
            pip install awscli
            export AWS_ACCESS_KEY_ID=Some_Key
            export AWS_SECRET_ACCESS_KEY=Some_Secret_Key
            export AWS_DEFAULT_REGION=ca-central-1
            export AWS_DEFAULT_OUTPUT=json
      - run:
          name: Start up DynamoDB local
          command:
            java -Djava.library.pathh=./DynamoDBLocal_lib/ -jar DynamoDBLocal.jar -sharedDb
          background: true
          
          
